question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "To bypass US Munitions Export Laws, the creator of the PGP published all "
                    "the source code in book form. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"]
    },
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "&quot;Windows NT&quot; is a monolithic kernel.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                       "question": "The first dual-core CPU was the Intel Pentium D.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "The open source program Redis is a relational database server.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Android versions are named in alphabetical order.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                       "question": "The HTML5 standard was published in 2014.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "AMD created the first consumer 64-bit processor.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]}
]
